### ISSUE TITLE
Small documentation issue

### ISSUE THREAD

**Issue by woutervanwijk** [lulupointu/vrouter_website#6]
Thanks for your great easy to use package and excellent documentation! One small issue: when I use the guide https://vrouter.dev/guide/ I cannot copy a line of code, I have to copy all, or nothing. I guess the guide is built using flutter too? Maybe use SelectableText for the code examples?

**Comment by lulupointu** [comment]
Fixed as much as possible. The code is now selectable (this is an issue with the plugin I use as expected so I had to use some tricks).

However there are some bad things happening like when you select+scroll it behaves weirdly. I think this is because of flutter and the way SelectableText are coded though, but I don't really have the time to open an issue about this.
